trigger:
  - main

pool:
  name: Default # Update if your agent pool is not named 'Default'

steps:
  # Step 1: Install .NET SDK (Ensure .NET 8 SDK is used)
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with NuGet'

  # Step 3: Pack the NuGet package
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet Package'
    inputs:
      command: 'pack'
      projects: '/Users/nychollas/Documents/Centennial/COMP367/LAB4/StringExtensionsLibrary/StringExtensionsLibrary.csproj'
      arguments: '--output $(Build.ArtifactStagingDirectory)'


  # Step 2: Authenticate with NuGet (for Linux agents)
  - task: NuGetAuthenticate@1
    name: 'NYchollas'
    displayName: 'Authenticate with NuGet'
    
  # Step 4: Push the NuGet package to a feed
  - task: DotNetCoreCLI@2
    inputs:
      command: 'dotnet nuget add source "https://pkgs.dev.azure.com/ndellamo0158/_packaging/ndellamo0158/nuget/v3/index.json"  --username "ndellamo0158" --password "AzrFjat11DwXnPyu5qYgYnaZerxlyGD8M26tWEOGV8KBp9IEdZ0pJQQJ99ALACAAAAAnPw96AAASAZDOepus"'

      