
trigger:
  - main

pool:
  name: Default # Update if your agent pool is not named 'Default'

steps:
  # Step 1: Install .NET SDK (Ensure .NET 8 SDK is used)
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet Package'
    inputs:
      command: 'pack'
      projects: '/Users/nychollas/Documents/Centennial/COMP367/LAB4/StringExtensionsLibrary/StringExtensionsLibrary.csproj'
      arguments: '--output $(Build.ArtifactStagingDirectory)'
  
  # - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" --source https://pkgs.dev.azure.com/ndellamo0158/_packaging/ndellamo0158/nuget/v3/index.json --api-key AzureArtifacts --skip-duplicate
  - script: /opt/homebrew/bin/mono /Users/nychollas/myagent2/_work/_tool/NuGet/4.9.6/x64/nuget.exe push /Users/nychollas/myagent2/_work/2/a/StringExtensionsLibrary.1.0.0.nupkg -NonInteractive -Source https://pkgs.dev.azure.com/ndellamo0158/_packaging/ndellamo0158/nuget/v3/index.json -ApiKey VSTS -Verbosity Detailed
