trigger:
  - main

pool:
  name: Default # Update if your agent pool is not named 'Default'

steps:
  # Step 1: Install .NET SDK (Ensure .NET 8 SDK is used)
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with NuGet'

  # Step 3: Pack the NuGet package
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet Package'
    inputs:
      command: 'pack'
      projects: '/Users/nychollas/Documents/Centennial/COMP367/LAB4/Lab4ConsoleApp/Lab4ConsoleApp.csproj'
      arguments: '--output $(Build.ArtifactStagingDirectory)'


  # Step 2: Authenticate with NuGet (for Linux agents)
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with NuGet'
    
  # Step 4: Push the NuGet package to a feed
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'd6307433-fd35-4fb9-933f-59e64efb3658'
      allowPackageConflicts: true