trigger:
- main

pool:
  name: 'Default' # Replace with your self-hosted agent pool name

variables:
  BuildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: |
    dotnet restore
    dotnet build --configuration $(BuildConfiguration)
    dotnet pack --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Build and Pack NuGet Package'

- script: |
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" \
      --source "https://pkgs.dev.azure.com/<organization>/<project>/_packaging/<feed>/nuget/v3/index.json" \
      --api-key "AzureDevOps"
  displayName: 'Push NuGet Package'
