trigger:
  - main

pool:
  name: Default # Ensure this matches your self-hosted agent's pool name

steps:
  # Step 1: Install .NET SDK (Ensure .NET 8 SDK is used)
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Step 2: Restore NuGet packages (optional but recommended for build dependencies)
  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'

  # Step 3: Pack the NuGet package
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet Package'
    inputs:
      command: 'pack'
      projects: '**/StringExtensionsLibrary.csproj'
      arguments: '--output $(Build.ArtifactStagingDirectory)'

  # Step 4: Push the NuGet package to a feed

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'd6307433-fd35-4fb9-933f-59e64efb3658'
      allowPackageConflicts: true