trigger:
  - main

pool:
  name: Default # Ensure this matches your self-hosted agent's pool name

steps:
  # Step 1: Use the .NET SDK (Specify .NET 8 SDK)
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  
  - task: DotNetCoreCLI@2
    displayName: dotnet buuild
    inputs:
      command: 'build'
      projects: '**/StringExtensionsLibrary.csproj'
