trigger:
  - main

pool:
  name: Default # Ensure this matches your self-hosted agent's pool name

steps:
  # Step 1: Use the .NET SDK (Specify .NET 8 SDK)
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: DotNetCoreCLI@2
    displayName: 'Build MySpecificProject'
    inputs:
      command: 'build'
      projects: '**/Lab4ConsoleApp.csproj'
   

  - script: dotnet pack "**/StringExtensionsLibrary.csproj" --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack MySpecificProject as NuGet Package'

  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with NuGet'

  - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" --source https://pkgs.dev.azure.com/ndellamo0158/301259514(DellaMonicadaSilva)_Lab4/_packaging/Lab4feed/nuget/v3/index.json --api-key AzureArtifacts --skip-duplicate
    displayName: 'Push NuGet Package to Azure Artifacts'